### ISSUE TITLE
How do I get this to work?

### ISSUE THREAD

**Issue by Dacetylan** [Puukallistaja/turakas#1]
a nice README.md would be handy

it keeps on spamming this in the console, no game is created. Even when multiple users register

`request made`
`127.0.0.1`
`{ name: 'taraks' }`
`games running:`
`0`
`=============================================`

**Comment by Dacetylan** [comment]
I fixed it, the users ip adress was not visible when on localhost. I suggest changing `let ip = ...` to `let ip = req.headers['x-forwarded-for'] || req.connection.remoteAddress`

**Comment by Puukallistaja** [comment]
This repo is pretty much abandonware, only available for nostalgic reasons. I doubt that any changes will be introduced.
